// ಭಗವದ್ಗೀತಾ ಪಯಣ — verse data
// One essence-verse chosen from each of the 18 chapters.
// Structure is deliberately flat & simple so more verses can be added later —
// just copy an object below, keep the same keys, and push it into GITA_DATA.

const GITA_DATA = [
  {
    chapter: 1,
    chapterTitleKn: "ಅರ್ಜುನ ವಿಷಾದ ಯೋಗ",
    chapterTitleEn: "Arjuna's Despair",
    verseRef: "1.1",
    sanskrit: "ಧೃತರಾಷ್ಟ್ರ ಉವಾಚ\nಧರ್ಮಕ್ಷೇತ್ರೇ ಕುರುಕ್ಷೇತ್ರೇ ಸಮವೇತಾ ಯುಯುತ್ಸವಃ|\nಮಾಮಕಾಃ ಪಾಂಡವಾಶ್ಚೈವ ಕಿಮಕುರ್ವತ ಸಂಜಯ||",
    kannadaChant: "ಧೃತರಾಷ್ಟ್ರ ಉವಾಚ\nಧರ್ಮಕ್ಷೇತ್ರೇ ಕುರುಕ್ಷೇತ್ರೇ ಸಮವೇತಾ ಯುಯುತ್ಸವಃ|\nಮಾಮಕಾಃ ಪಾಂಡವಾಶ್ಚೈವ ಕಿಮಕುರ್ವತ ಸಂಜಯ||",
    meaningKn: "ಧೃತರಾಷ್ಟ್ರನು ಸಂಜಯನಲ್ಲಿ ಕೇಳುತ್ತಾನೆ: \"ಧರ್ಮಭೂಮಿಯಾದ ಕುರುಕ್ಷೇತ್ರದಲ್ಲಿ ಯುದ್ಧಕ್ಕೆ ಸಿದ್ಧರಾಗಿ ಸೇರಿದ ನನ್ನ ಮಕ್ಕಳು ಮತ್ತು ಪಾಂಡವರು ಏನು ಮಾಡಿದರು?\"",
    meaningEn: "Dhritarashtra asks Sanjaya: \"On the sacred field of Kurukshetra, when my sons and the sons of Pandu gathered, ready for battle, what did they do?\"",
    explanationKn: "ಇದು ಗೀತೆಯ ಆರಂಭ. ಎರಡು ಕುಟುಂಬಗಳು ಯುದ್ಧಕ್ಕೆ ಸಿದ್ಧವಾಗಿ ನಿಂತಿವೆ. ಈ ಭೂಮಿಯನ್ನು \"ಧರ್ಮಕ್ಷೇತ್ರ\" ಎಂದು ಕರೆದಿರುವುದರಿಂದ, ಇದು ಕೇವಲ ಯುದ್ಧವಲ್ಲ, ಸರಿಯಾದ ದಾರಿ ಆರಿಸುವ ಕಥೆ ಎಂದು ಮೊದಲೇ ಸೂಚನೆ ಸಿಗುತ್ತದೆ.",
    explanationEn: "This is where the Gita begins. Two families stand ready for war on a field that is also called \"dharma kshetra\" — the field of righteousness. The very first line hints that this story is not only about a battle, but about choosing the right path.",
    lifeHackKn: "ಜೀವನದ ಪ್ರತಿ ದೊಡ್ಡ ನಿರ್ಧಾರವೂ ಒಂದು \"ಕುರುಕ್ಷೇತ್ರ\" — ಸರಿ ಮತ್ತು ತಪ್ಪು ಹೋರಾಡುವ ಸ್ಥಳ. ನೀವು ಅಂತಹ ಸ್ಥಳದಲ್ಲಿ ಇದ್ದೀರಿ ಎಂದು ಮೊದಲು ಗುರುತಿಸಿ, ಆಮೇಲೆ ಕಾರ್ಯ ಮಾಡಿ.",
    lifeHackEn: "Every big decision in life is its own Kurukshetra — a field where right and wrong quietly fight it out. Notice when you're standing on one before you act."
  },
  {
    chapter: 2,
    chapterTitleKn: "ಸಾಂಖ್ಯ ಯೋಗ",
    chapterTitleEn: "The Yoga of Knowledge",
    verseRef: "2.47",
    sanskrit: "ಕರ್ಮಣ್ಯೇವಾಧಿಕಾರಸ್ತೇ ಮಾ ಫಲೇಷು ಕದಾಚನ|\nಮಾ ಕರ್ಮಫಲಹೇತುರ್ಭೂಃ ಮಾ ತೇ ಸಂಗೋಽಸ್ತ್ವಕರ್ಮಣಿ||",
    kannadaChant: "ಕರ್ಮಣ್ಯೇವಾಧಿಕಾರಸ್ತೇ ಮಾ ಫಲೇಷು ಕದಾಚನ|\nಮಾ ಕರ್ಮಫಲಹೇತುರ್ಭೂಃ ಮಾ ತೇ ಸಂಗೋಽಸ್ತ್ವಕರ್ಮಣಿ||",
    meaningKn: "ನಿಮಗೆ ಕರ್ಮ ಮಾಡುವ ಹಕ್ಕಿದೆ, ಆದರೆ ಅದರ ಫಲದ ಮೇಲೆ ಹಕ್ಕಿಲ್ಲ. ಫಲಕ್ಕಾಗಿ ಕೆಲಸ ಮಾಡಬೇಡಿ, ಕೆಲಸ ಮಾಡದಿರುವುದರಲ್ಲೂ ಆಸಕ್ತಿ ಇಡಬೇಡಿ.",
    meaningEn: "You have the right to perform your duty, but never to the fruits of your actions. Don't act for results, and don't be attached to inaction either.",
    explanationKn: "ಕೃಷ್ಣನು ಕರ್ಮಯೋಗದ ರಹಸ್ಯ ಹೇಳುತ್ತಾನೆ — ಪೂರ್ಣ ಪ್ರಯತ್ನ ಮಾಡಿ, ಆದರೆ ಫಲದ ಬಗ್ಗೆ ಚಿಂತೆ ಬಿಡಿ. ಫಲದ ಚಿಂತೆ ನಿಮ್ಮ ಗಮನವನ್ನು ಕೆಲಸದಿಂದ ದೂರ ಮಾಡುತ್ತದೆ.",
    explanationEn: "Krishna reveals the secret of karma yoga here — give your best effort, but let go of anxiety about the outcome. Worrying about results only steals focus from the work itself.",
    lifeHackKn: "ಪ್ರಯತ್ನದ ಮೇಲೆ 100% ಗಮನ, ಫಲದ ಚಿಂತೆಯ ಮೇಲೆ 0%. ಇದೇ ಒತ್ತಡ-ಮುಕ್ತ ಜೀವನದ ಸೂತ್ರ.",
    lifeHackEn: "Put 100% of your focus into the effort and 0% into outcome-anxiety. This single line is one of the best stress-management tools ever written."
  },
  {
    chapter: 3,
    chapterTitleKn: "ಕರ್ಮ ಯೋಗ",
    chapterTitleEn: "The Yoga of Action",
    verseRef: "3.21",
    sanskrit: "ಯದ್ಯದಾಚರತಿ ಶ್ರೇಷ್ಠಸ್ತತ್ತದೇವೇತರೋ ಜನಃ|\nಸ ಯತ್ಪ್ರಮಾಣಂ ಕುರುತೇ ಲೋಕಸ್ತದನುವರ್ತತೇ||",
    kannadaChant: "ಯದ್ಯದಾಚರತಿ ಶ್ರೇಷ್ಠಸ್ತತ್ತದೇವೇತರೋ ಜನಃ|\nಸ ಯತ್ಪ್ರಮಾಣಂ ಕುರುತೇ ಲೋಕಸ್ತದನುವರ್ತತೇ||",
    meaningKn: "ಶ್ರೇಷ್ಠರು ಏನು ಮಾಡುತ್ತಾರೋ, ಅದನ್ನೇ ಇತರರು ಅನುಸರಿಸುತ್ತಾರೆ. ಅವರು ಹಾಕುವ ಮಾನದಂಡವನ್ನೇ ಲೋಕ ಅನುಸರಿಸುತ್ತದೆ.",
    meaningEn: "Whatever a great person does, others follow. Whatever standard they set, the whole world follows it.",
    explanationKn: "ನಾಯಕರು, ಪೋಷಕರು, ಗುರುಗಳು ತಮ್ಮ ಮಾತಿನಿಂದಲ್ಲ, ಕ್ರಿಯೆಯಿಂದ ಇತರರನ್ನು ರೂಪಿಸುತ್ತಾರೆ. ನಿಮ್ಮ ಕ್ರಿಯೆಗಳು ನಿಮ್ಮನ್ನು ನೋಡುವ ಎಲ್ಲರಿಗೂ ಮೌನವಾಗಿ ಪಾಠ ಕಲಿಸುತ್ತವೆ.",
    explanationEn: "Leaders, parents and teachers shape behaviour simply by what they do, not just what they say. Your actions quietly teach everyone who is watching you — whether you intend it or not.",
    lifeHackKn: "ಸಲಹೆಗಾರರಾಗಿರುವುದಕ್ಕಿಂತ ಮಾದರಿಯಾಗಿರಿ. ಜನರು ನೀವು ಹೇಳುವುದಕ್ಕಿಂತ ಮಾಡುವುದನ್ನೇ ಹೆಚ್ಚು ಅನುಸರಿಸುತ್ತಾರೆ.",
    lifeHackEn: "Be the example, not just the advisor. People copy what you do far more closely than what you say."
  },
  {
    chapter: 4,
    chapterTitleKn: "ಜ್ಞಾನ ಕರ್ಮ ಸಂನ್ಯಾಸ ಯೋಗ",
    chapterTitleEn: "Knowledge & Action",
    verseRef: "4.7",
    sanskrit: "ಯದಾ ಯದಾ ಹಿ ಧರ್ಮಸ್ಯ ಗ್ಲಾನಿರ್ಭವತಿ ಭಾರತ|\nಅಭ್ಯುತ್ಥಾನಮಧರ್ಮಸ್ಯ ತದಾತ್ಮಾನಂ ಸೃಜಾಮ್ಯಹಮ್||",
    kannadaChant: "ಯದಾ ಯದಾ ಹಿ ಧರ್ಮಸ್ಯ ಗ್ಲಾನಿರ್ಭವತಿ ಭಾರತ|\nಅಭ್ಯುತ್ಥಾನಮಧರ್ಮಸ್ಯ ತದಾತ್ಮಾನಂ ಸೃಜಾಮ್ಯಹಮ್||",
    meaningKn: "ಯಾವಾಗ ಧರ್ಮ ಕುಗ್ಗುತ್ತದೋ ಮತ್ತು ಅಧರ್ಮ ಹೆಚ್ಚುತ್ತದೋ, ಆಗ ನಾನು ಅವತರಿಸುತ್ತೇನೆ, ಭಾರತ.",
    meaningEn: "Whenever righteousness declines and unrighteousness rises, O Bharata, I manifest myself.",
    explanationKn: "ಎಷ್ಟೇ ಕೆಟ್ಟದ್ದು ಗೆಲ್ಲುತ್ತಿದೆ ಎಂದು ಕಂಡರೂ, ಸಮತೋಲನ ಯಾವಾಗಲೂ ಹಿಂತಿರುಗುತ್ತದೆ. ಒಳ್ಳೆಯದನ್ನು ಮರಳಿ ತರುವ ಶಕ್ತಿ ಲೋಕದಲ್ಲಿ ಮತ್ತು ನಮ್ಮೊಳಗೂ ಏಳುತ್ತದೆ.",
    explanationEn: "Balance always returns, even when it looks lost. Whenever wrong seems to be winning, a force for good eventually rises to restore order — in the world, and quietly within us too.",
    lifeHackKn: "ಪರಿಸ್ಥಿತಿ ಅಸ್ತವ್ಯಸ್ತವಾಗಿ ಕಂಡಾಗ, ಸಮತೋಲನ ಮರಳುತ್ತದೆ ಎಂದು ನಂಬಿ — ಬಿಟ್ಟುಬಿಡುವ ಬದಲು, ಅದನ್ನು ಸರಿಪಡಿಸಲು ನಿಮ್ಮ ಪಾತ್ರ ಏನೆಂದು ಯೋಚಿಸಿ.",
    lifeHackEn: "When things feel chaotic or unfair, trust that balance returns — and ask what part you can play in restoring it, instead of giving up."
  },
  {
    chapter: 5,
    chapterTitleKn: "ಕರ್ಮ ಸಂನ್ಯಾಸ ಯೋಗ",
    chapterTitleEn: "The Yoga of Renunciation",
    verseRef: "5.10",
    sanskrit: "ಬ್ರಹ್ಮಣ್ಯಾಧಾಯ ಕರ್ಮಾಣಿ ಸಂಗಂ ತ್ಯಕ್ತ್ವಾ ಕರೋತಿ ಯಃ|\nಲಿಪ್ಯತೇ ನ ಸ ಪಾಪೇನ ಪದ್ಮಪತ್ರಮಿವಾಂಭಸಾ||",
    kannadaChant: "ಬ್ರಹ್ಮಣ್ಯಾಧಾಯ ಕರ್ಮಾಣಿ ಸಂಗಂ ತ್ಯಕ್ತ್ವಾ ಕರೋತಿ ಯಃ|\nಲಿಪ್ಯತೇ ನ ಸ ಪಾಪೇನ ಪದ್ಮಪತ್ರಮಿವಾಂಭಸಾ||",
    meaningKn: "ಕರ್ಮಗಳನ್ನು ಭಗವಂತನಿಗೆ ಅರ್ಪಿಸಿ, ಆಸಕ್ತಿ ಇಲ್ಲದೆ ಮಾಡುವವನು ಪಾಪದಿಂದ ಅಂಟಿಕೊಳ್ಳುವುದಿಲ್ಲ — ನೀರಿನಲ್ಲಿದ್ದರೂ ಒದ್ದೆಯಾಗದ ತಾವರೆ ಎಲೆಯಂತೆ.",
    meaningEn: "One who acts offering every action to the Divine, without attachment, remains untouched by it — like a lotus leaf that stays dry even while resting on water.",
    explanationKn: "ಕೆಲಸ ಮಾಡುವಾಗ \"ಇದು ನನಗಾಗಿ\" ಎಂಬ ಅಹಂಕಾರವಿಲ್ಲದೆ, ಸ್ಪಷ್ಟ ಮನಸ್ಸಿನಿಂದ ಮಾಡುವುದು ನಿಮ್ಮನ್ನು ಹಗುರವಾಗಿ, ಭಾರವಿಲ್ಲದೆ ಇಡುತ್ತದೆ.",
    explanationEn: "Doing your work with a clear heart, without the ego insisting \"I did this for me,\" keeps you light and unburdened — even while you stay fully active in the world.",
    lifeHackKn: "ನೀರಿನಲ್ಲಿರುವ ತಾವರೆ ಎಲೆಯಂತೆ ಜಗತ್ತಿನಲ್ಲಿ ಇರಿ — ಪೂರ್ಣವಾಗಿ ತೊಡಗಿಸಿಕೊಂಡಿದ್ದರೂ ಒತ್ತಡ, ಅಹಂಕಾರದಿಂದ ಒದ್ದೆಯಾಗಬೇಡಿ.",
    lifeHackEn: "Stay engaged with the world like a lotus leaf on water — fully present, but never soaked through by stress, ego, or outcomes."
  },
  {
    chapter: 6,
    chapterTitleKn: "ಧ್ಯಾನ ಯೋಗ",
    chapterTitleEn: "The Yoga of Meditation",
    verseRef: "6.5",
    sanskrit: "ಉದ್ಧರೇದಾತ್ಮನಾತ್ಮಾನಂ ನಾತ್ಮಾನಮವಸಾದಯೇತ್|\nಆತ್ಮೈವ ಹ್ಯಾತ್ಮನೋ ಬಂಧುರಾತ್ಮೈವ ರಿಪುರಾತ್ಮನಃ||",
    kannadaChant: "ಉದ್ಧರೇದಾತ್ಮನಾತ್ಮಾನಂ ನಾತ್ಮಾನಮವಸಾದಯೇತ್|\nಆತ್ಮೈವ ಹ್ಯಾತ್ಮನೋ ಬಂಧುರಾತ್ಮೈವ ರಿಪುರಾತ್ಮನಃ||",
    meaningKn: "ನಿಮ್ಮನ್ನು ನೀವೇ ಮೇಲೆತ್ತಿಕೊಳ್ಳಿ, ನೀವೇ ಕುಗ್ಗಿಸಿಕೊಳ್ಳಬೇಡಿ. ಮನಸ್ಸೇ ನಿಮ್ಮ ಸ್ನೇಹಿತ, ಮನಸ್ಸೇ ನಿಮ್ಮ ಶತ್ರು.",
    meaningEn: "Lift yourself by your own self; do not drag yourself down. The self alone is the friend of the self, and the self alone is its enemy.",
    explanationKn: "ನಿಮ್ಮ ದೊಡ್ಡ ಬೆಂಬಲಿಗ ಮತ್ತು ದೊಡ್ಡ ಅಡ್ಡಿ ಎರಡೂ ನಿಮ್ಮೊಳಗೇ ಇದೆ — ನಿಮ್ಮ ಮನಸ್ಸು. ಶಿಸ್ತು ಮನಸ್ಸನ್ನು ಸ್ನೇಹಿತನಾಗಿ ಮಾಡುತ್ತದೆ, ನಿರ್ಲಕ್ಷ್ಯ ಶತ್ರುವಾಗಿ ಮಾಡುತ್ತದೆ.",
    explanationEn: "Your biggest supporter and your biggest obstacle both live inside you — your own mind. Discipline turns the mind into a friend; carelessness slowly turns it into an enemy.",
    lifeHackKn: "ನಿಮ್ಮ ದೊಡ್ಡ ಶತ್ರುವನ್ನು ಅಥವಾ ರಕ್ಷಕನನ್ನು ಹೊರಗೆ ಹುಡುಕುವುದು ನಿಲ್ಲಿಸಿ — ಮೊದಲು ನಿಮ್ಮ ಮನಸ್ಸನ್ನು ತರಬೇತುಗೊಳಿಸಿ.",
    lifeHackEn: "Stop searching outside for your biggest enemy or saviour. Start by training your own mind — that's where both really live."
  },
  {
    chapter: 7,
    chapterTitleKn: "ಜ್ಞಾನ ವಿಜ್ಞಾನ ಯೋಗ",
    chapterTitleEn: "Knowledge & Wisdom",
    verseRef: "7.7",
    sanskrit: "ಮತ್ತಃ ಪರತರಂ ನಾನ್ಯತ್ಕಿಂಚಿದಸ್ತಿ ಧನಂಜಯ|\nಮಯಿ ಸರ್ವಮಿದಂ ಪ್ರೋತಂ ಸೂತ್ರೇ ಮಣಿಗಣಾ ಇವ||",
    kannadaChant: "ಮತ್ತಃ ಪರತರಂ ನಾನ್ಯತ್ಕಿಂಚಿದಸ್ತಿ ಧನಂಜಯ|\nಮಯಿ ಸರ್ವಮಿದಂ ಪ್ರೋತಂ ಸೂತ್ರೇ ಮಣಿಗಣಾ ಇವ||",
    meaningKn: "ನನಗಿಂತ ಮಿಗಿಲಾದುದು ಏನೂ ಇಲ್ಲ, ಅರ್ಜುನ. ಎಲ್ಲವೂ ದಾರದಲ್ಲಿ ಮುತ್ತುಗಳಂತೆ ನನ್ನಲ್ಲಿ ಪೋಣಿಸಲ್ಪಟ್ಟಿವೆ.",
    meaningEn: "There is nothing higher than Me, O Dhananjaya. Everything that exists is strung on Me, like pearls on a single thread.",
    explanationKn: "ಜಗತ್ತಿನ ಎಲ್ಲ ವೈವಿಧ್ಯತೆಯ ಹಿಂದೆ — ಜನರು, ಘಟನೆಗಳು, ವಸ್ತುಗಳು — ಒಂದು ಸಂಪರ್ಕ ದಾರ ಇದೆ. ಯಾವುದೂ ನಿಜವಾಗಿ ಪ್ರತ್ಯೇಕವಲ್ಲ.",
    explanationEn: "Behind all the variety of the world — people, events, objects — there runs one connecting thread. Nothing is ever truly separate, even when it feels that way.",
    lifeHackKn: "ಜೀವನ ಚದುರಿದಂತೆ ಕಂಡಾಗ, ಎಲ್ಲವೂ ಒಂದು ದಾರದಿಂದ ಸಂಪರ್ಕಿತ ಎಂದು ನೆನಪಿಡಿ — ಒಂದು ಮುರಿದ ಮಣಿಗಾಗಿ ಆತಂಕಪಡುವ ಮೊದಲು ದೊಡ್ಡ ಚಿತ್ರ ನೋಡಿ.",
    lifeHackEn: "When life feels scattered, remember everything is strung on one thread — zoom out and see the whole necklace before panicking over one loose bead."
  },
  {
    chapter: 8,
    chapterTitleKn: "ಅಕ್ಷರ ಬ್ರಹ್ಮ ಯೋಗ",
    chapterTitleEn: "The Imperishable",
    verseRef: "8.7",
    sanskrit: "ತಸ್ಮಾತ್ಸರ್ವೇಷು ಕಾಲೇಷು ಮಾಮನುಸ್ಮರ ಯುಧ್ಯ ಚ|\nಮಯ್ಯರ್ಪಿತಮನೋಬುದ್ಧಿರ್ಮಾಮೇವೈಷ್ಯಸ್ಯಸಂಶಯಮ್||",
    kannadaChant: "ತಸ್ಮಾತ್ಸರ್ವೇಷು ಕಾಲೇಷು ಮಾಮನುಸ್ಮರ ಯುಧ್ಯ ಚ|\nಮಯ್ಯರ್ಪಿತಮನೋಬುದ್ಧಿರ್ಮಾಮೇವೈಷ್ಯಸ್ಯಸಂಶಯಮ್||",
    meaningKn: "ಆದ್ದರಿಂದ ಎಲ್ಲಾ ಕಾಲದಲ್ಲೂ ನನ್ನನ್ನು ಸ್ಮರಿಸಿ ಹೋರಾಡು. ಮನಸ್ಸು ಬುದ್ಧಿಯನ್ನು ನನ್ನಲ್ಲಿ ಅರ್ಪಿಸಿದರೆ ನೀನು ನಿಶ್ಚಯವಾಗಿ ನನ್ನನ್ನು ಸೇರುವೆ.",
    meaningEn: "Therefore, at all times remember Me and keep doing your work. With mind and intellect fixed on Me, you will surely reach Me.",
    explanationKn: "ಆಧ್ಯಾತ್ಮಿಕವಾಗಿ ಬೆಳೆಯಲು ಜೀವನ ನಿಲ್ಲಿಸಬೇಕಿಲ್ಲ. ದಿನನಿತ್ಯದ ಕೆಲಸ ಮಾಡುತ್ತಲೇ, ಒಳಗೆ ಸ್ಥಿರವಾದ ಒಂದು ಆಧಾರ ಇಟ್ಟುಕೊಳ್ಳಿ.",
    explanationEn: "You don't need to stop living your life to grow spiritually. Keep a steady inner anchor while you carry on with your daily duties — remember what matters even as you act.",
    lifeHackKn: "ದಿನನಿತ್ಯದ ಗೊಂದಲದ ನಡುವೆಯೂ ಒಂದು ಸ್ಥಿರ ಆಧಾರ (ಮೌಲ್ಯ, ಅಭ್ಯಾಸ, ವ್ಯಕ್ತಿ) ಮನಸ್ಸಿನಲ್ಲಿಟ್ಟುಕೊಳ್ಳಿ.",
    lifeHackEn: "Keep one steady anchor — a value, a habit, a person — in mind while you handle daily chaos. It keeps you grounded without needing to escape life."
  },
  {
    chapter: 9,
    chapterTitleKn: "ರಾಜ ವಿದ್ಯಾ ರಾಜ ಗುಹ್ಯ ಯೋಗ",
    chapterTitleEn: "Royal Knowledge",
    verseRef: "9.22",
    sanskrit: "ಅನನ್ಯಾಶ್ಚಿಂತಯಂತೋ ಮಾಂ ಯೇ ಜನಾಃ ಪರ್ಯುಪಾಸತೇ|\nತೇಷಾಂ ನಿತ್ಯಾಭಿಯುಕ್ತಾನಾಂ ಯೋಗಕ್ಷೇಮಂ ವಹಾಮ್ಯಹಮ್||",
    kannadaChant: "ಅನನ್ಯಾಶ್ಚಿಂತಯಂತೋ ಮಾಂ ಯೇ ಜನಾಃ ಪರ್ಯುಪಾಸತೇ|\nತೇಷಾಂ ನಿತ್ಯಾಭಿಯುಕ್ತಾನಾಂ ಯೋಗಕ್ಷೇಮಂ ವಹಾಮ್ಯಹಮ್||",
    meaningKn: "ಬೇರೇನೂ ಯೋಚಿಸದೆ, ಕೇವಲ ನನ್ನನ್ನೇ ಸ್ಥಿರವಾಗಿ ಆರಾಧಿಸುವವರಿಗೆ, ಅವರಿಗೆ ಇಲ್ಲದ್ದನ್ನು ನಾನು ತಂದುಕೊಡುತ್ತೇನೆ, ಇರುವುದನ್ನು ಕಾಪಾಡುತ್ತೇನೆ.",
    meaningEn: "To those who worship Me alone, thinking of nothing else, ever steadfast, I carry what they lack and preserve what they already have.",
    explanationKn: "ಒಂದು ನಿಜವಾದ ಗುರಿಯ ಮೇಲೆ ಆಳವಾದ, ಕೇಂದ್ರೀಕೃತ ಬದ್ಧತೆ, ಚದುರಿದ ಪ್ರಯತ್ನಕ್ಕಿಂತ ಹೆಚ್ಚು ಬೆಂಬಲ ಮತ್ತು ಭದ್ರತೆ ತರುತ್ತದೆ.",
    explanationEn: "Deep, focused commitment to one true priority brings a kind of support and security that scattered, half-hearted effort never can.",
    lifeHackKn: "ನಿಮ್ಮ ಮುಖ್ಯ ಆದ್ಯತೆ ಆರಿಸಿ, ಅದಕ್ಕೆ ಪೂರ್ಣ ಗಮನ ಕೊಡಿ — ಕೇಂದ್ರೀಕೃತ ಬದ್ಧತೆಗೆ ಜೀವನ ಹೆಚ್ಚು ಬೆಂಬಲ ನೀಡುತ್ತದೆ.",
    lifeHackEn: "Pick your top priority and give it undivided focus — focused dedication tends to pull in far more support than spreading yourself thin."
  },
  {
    chapter: 10,
    chapterTitleKn: "ವಿಭೂತಿ ಯೋಗ",
    chapterTitleEn: "Divine Glories",
    verseRef: "10.20",
    sanskrit: "ಅಹಮಾತ್ಮಾ ಗುಡಾಕೇಶ ಸರ್ವಭೂತಾಶಯಸ್ಥಿತಃ|\nಅಹಮಾದಿಶ್ಚ ಮಧ್ಯಂ ಚ ಭೂತಾನಾಮಂತ ಏವ ಚ||",
    kannadaChant: "ಅಹಮಾತ್ಮಾ ಗುಡಾಕೇಶ ಸರ್ವಭೂತಾಶಯಸ್ಥಿತಃ|\nಅಹಮಾದಿಶ್ಚ ಮಧ್ಯಂ ಚ ಭೂತಾನಾಮಂತ ಏವ ಚ||",
    meaningKn: "ನಾನು ಆತ್ಮ, ಎಲ್ಲಾ ಜೀವಿಗಳ ಹೃದಯದಲ್ಲಿ ನೆಲೆಸಿದ್ದೇನೆ. ನಾನೇ ಎಲ್ಲಾ ಜೀವಿಗಳ ಆದಿ, ಮಧ್ಯ ಮತ್ತು ಅಂತ್ಯ.",
    meaningEn: "I am the Self, seated in the hearts of all beings. I am the beginning, the middle, and the end of all that exists.",
    explanationKn: "ಅದೇ ದೈವಿಕ ಅಂಶ ಪ್ರತಿಯೊಂದು ಜೀವಿಯಲ್ಲೂ ಇದೆ — ಹಾಗಾಗಿ ಯಾರೂ ನಿಜವಾಗಿ ಹೊರಗಿನವರಲ್ಲ. ಇತರರನ್ನು ಗೌರವಿಸುವುದೇ ನಿಮ್ಮೊಳಗಿನ ಅದೇ ಮೂಲವನ್ನು ಗೌರವಿಸಿದಂತೆ.",
    explanationEn: "The same divine presence lives in every being, so no one is ever a true outsider. Respecting someone else is, in a quiet way, respecting the same source that lives in you.",
    lifeHackKn: "ನೀವು ಭೇಟಿಯಾಗುವ ಪ್ರತಿಯೊಬ್ಬರನ್ನೂ ನಿಮ್ಮಲ್ಲಿರುವ ಅದೇ ಕಿಡಿಯನ್ನು ಹೊಂದಿರುವವರು ಎಂದು ಪರಿಗಣಿಸಿ.",
    lifeHackEn: "Treat every person you meet as carrying the same spark you carry — it quietly softens judgment and anger before they even start."
  },
  {
    chapter: 11,
    chapterTitleKn: "ವಿಶ್ವರೂಪ ದರ್ಶನ ಯೋಗ",
    chapterTitleEn: "The Universal Form",
    verseRef: "11.32",
    sanskrit: "ಕಾಲೋಽಸ್ಮಿ ಲೋಕಕ್ಷಯಕೃತ್ಪ್ರವೃದ್ಧೋ ಲೋಕಾನ್ಸಮಾಹರ್ತುಮಿಹ ಪ್ರವೃತ್ತಃ|\nಋತೇಽಪಿ ತ್ವಾಂ ನ ಭವಿಷ್ಯಂತಿ ಸರ್ವೇ ಯೇಽವಸ್ಥಿತಾಃ ಪ್ರತ್ಯನೀಕೇಷು ಯೋಧಾಃ||",
    kannadaChant: "ಕಾಲೋಽಸ್ಮಿ ಲೋಕಕ್ಷಯಕೃತ್ಪ್ರವೃದ್ಧೋ ಲೋಕಾನ್ಸಮಾಹರ್ತುಮಿಹ ಪ್ರವೃತ್ತಃ|\nಋತೇಽಪಿ ತ್ವಾಂ ನ ಭವಿಷ್ಯಂತಿ ಸರ್ವೇ ಯೇಽವಸ್ಥಿತಾಃ ಪ್ರತ್ಯನೀಕೇಷು ಯೋಧಾಃ||",
    meaningKn: "ನಾನು ಕಾಲ, ಲೋಕಗಳನ್ನು ನಾಶಮಾಡುವ ಮಹಾಶಕ್ತಿ, ಈ ಸೈನ್ಯಗಳನ್ನು ಸಂಹರಿಸಲು ಬಂದಿದ್ದೇನೆ. ನೀನಿಲ್ಲದಿದ್ದರೂ ಈ ಯೋಧರು ಉಳಿಯುವುದಿಲ್ಲ.",
    meaningEn: "I am time, the mighty destroyer of worlds, here to annihilate these armies. Even without you, none of these warriors arrayed for battle will survive.",
    explanationKn: "ಕೃಷ್ಣ ತನ್ನ ವಿಶ್ವರೂಪ ತೋರಿಸುತ್ತಾನೆ — ಕಾಲವೇ, ತಡೆಯಲಾಗದ ಶಕ್ತಿ. ಬದಲಾವಣೆ, ಕಾಲ, ವಿಧಿ ನಮ್ಮ ಆಯ್ಕೆಗಳ ಹೊರತಾಗಿಯೂ ಚಲಿಸುತ್ತಲೇ ಇರುತ್ತದೆ ಎಂಬ ನೆನಪು.",
    explanationEn: "Krishna reveals his cosmic form here — time itself, unstoppable. It's a reminder that larger forces like change and time keep moving regardless of our individual choices.",
    lifeHackKn: "ಕಾಲ ಈಗಾಗಲೇ ನಿರ್ಧರಿಸಿದ್ದನ್ನು ವಿರೋಧಿಸುವುದು ನಿಲ್ಲಿಸಿ — ತಪ್ಪಿಸಲಾಗದ್ದರ ವಿರುದ್ಧ ಹೋರಾಡುವ ಬದಲು ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯ ಮೇಲೆ ಗಮನ ಕೊಡಿ.",
    lifeHackEn: "Stop fighting what time has already set in motion. Put your energy into how you respond, not into resisting the inevitable."
  },
  {
    chapter: 12,
    chapterTitleKn: "ಭಕ್ತಿ ಯೋಗ",
    chapterTitleEn: "The Yoga of Devotion",
    verseRef: "12.15",
    sanskrit: "ಯಸ್ಮಾನ್ನೋದ್ವಿಜತೇ ಲೋಕೋ ಲೋಕಾನ್ನೋದ್ವಿಜತೇ ಚ ಯಃ|\nಹರ್ಷಾಮರ್ಷಭಯೋದ್ವೇಗೈರ್ಮುಕ್ತೋ ಯಃ ಸ ಚ ಮೇ ಪ್ರಿಯಃ||",
    kannadaChant: "ಯಸ್ಮಾನ್ನೋದ್ವಿಜತೇ ಲೋಕೋ ಲೋಕಾನ್ನೋದ್ವಿಜತೇ ಚ ಯಃ|\nಹರ್ಷಾಮರ್ಷಭಯೋದ್ವೇಗೈರ್ಮುಕ್ತೋ ಯಃ ಸ ಚ ಮೇ ಪ್ರಿಯಃ||",
    meaningKn: "ಯಾರು ಲೋಕವನ್ನು ಕಾಡುವುದಿಲ್ಲವೋ, ಲೋಕದಿಂದ ಕಾಡಲ್ಪಡುವುದಿಲ್ಲವೋ, ಹರ್ಷ, ಅಸೂಯೆ, ಭಯ, ಆತಂಕಗಳಿಂದ ಮುಕ್ತರೋ ಅವರು ನನಗೆ ಪ್ರಿಯರು.",
    meaningEn: "One who does not disturb the world, and is not disturbed by the world, who is free from excess joy, envy, fear and anxiety — that person is dear to Me.",
    explanationKn: "ನಿಜವಾದ ಪ್ರಬುದ್ಧತೆ ಎಂದರೆ ಭಾವನಾತ್ಮಕ ಸ್ಥಿರತೆ — ಇತರರಿಗೆ ತೊಂದರೆ ಕೊಡದಿರುವುದು, ಇತರರ ತೊಂದರೆಯಿಂದ ತೊಳಲಾಡದಿರುವುದು.",
    explanationEn: "True maturity looks like emotional steadiness — not creating chaos for others, and not being thrown off balance by the chaos others create.",
    lifeHackKn: "ಶಾಂತ ಇರುವ ಅಭ್ಯಾಸ ಮಾಡಿ — ಡ್ರಾಮಾ ಸೃಷ್ಟಿಸಬೇಡಿ, ಇತರರ ಡ್ರಾಮಾ ನಿಮ್ಮ ಶಾಂತಿಯನ್ನು ನಿಯಂತ್ರಿಸಲು ಬಿಡಬೇಡಿ.",
    lifeHackEn: "Practice being a calm presence — don't create drama, and don't let other people's drama rent space in your peace."
  },
  {
    chapter: 13,
    chapterTitleKn: "ಕ್ಷೇತ್ರ ಕ್ಷೇತ್ರಜ್ಞ ವಿಭಾಗ ಯೋಗ",
    chapterTitleEn: "The Field & Its Knower",
    verseRef: "13.27",
    sanskrit: "ಸಮಂ ಸರ್ವೇಷು ಭೂತೇಷು ತಿಷ್ಠಂತಂ ಪರಮೇಶ್ವರಮ್|\nವಿನಶ್ಯತ್ಸ್ವವಿನಶ್ಯಂತಂ ಯಃ ಪಶ್ಯತಿ ಸ ಪಶ್ಯತಿ||",
    kannadaChant: "ಸಮಂ ಸರ್ವೇಷು ಭೂತೇಷು ತಿಷ್ಠಂತಂ ಪರಮೇಶ್ವರಮ್|\nವಿನಶ್ಯತ್ಸ್ವವಿನಶ್ಯಂತಂ ಯಃ ಪಶ್ಯತಿ ಸ ಪಶ್ಯತಿ||",
    meaningKn: "ನಾಶವಾಗುವ ಎಲ್ಲದರಲ್ಲೂ ನಾಶವಿಲ್ಲದ ಪರಮಾತ್ಮನನ್ನು ಸಮನಾಗಿ ಕಾಣುವವನೇ ನಿಜವಾಗಿ ಕಾಣುವವನು.",
    meaningEn: "One who sees the same Supreme Lord equally present in all beings, imperishable within the perishable — that person truly sees.",
    explanationKn: "ದೇಹಗಳು, ಪರಿಸ್ಥಿತಿಗಳು, ಸಂಬಂಧಗಳು ಬದಲಾಗುತ್ತವೆ, ಕೊನೆಗೊಳ್ಳುತ್ತವೆ — ಆದರೆ ಅವುಗಳ ಹಿಂದಿನ ಬದಲಾಗದ ಸತ್ಯವನ್ನು ಕಾಣುವುದೇ ನಿಜವಾದ ಒಳನೋಟ.",
    explanationEn: "Bodies, situations and relationships change and end — but seeing the unchanging truth behind them is real insight, not just looking with your eyes.",
    lifeHackKn: "ನಿಮ್ಮ ಸುತ್ತಲಿನ ವಸ್ತು ಅಥವಾ ಜನರು ಬದಲಾದಾಗ, ಸ್ಥಿರವಾಗಿ ಉಳಿಯುವುದನ್ನು (ಮೌಲ್ಯ, ಪ್ರೀತಿ, ಸತ್ಯ) ಹುಡುಕಿ.",
    lifeHackEn: "When things or people around you change, look for what stays constant — values, love, truth. That's where real stability actually lives."
  },
  {
    chapter: 14,
    chapterTitleKn: "ಗುಣತ್ರಯ ವಿಭಾಗ ಯೋಗ",
    chapterTitleEn: "The Three Gunas",
    verseRef: "14.5",
    sanskrit: "ಸತ್ತ್ವಂ ರಜಸ್ತಮ ಇತಿ ಗುಣಾಃ ಪ್ರಕೃತಿಸಂಭವಾಃ|\nನಿಬಧ್ನಂತಿ ಮಹಾಬಾಹೋ ದೇಹೇ ದೇಹಿನಮವ್ಯಯಮ್||",
    kannadaChant: "ಸತ್ತ್ವಂ ರಜಸ್ತಮ ಇತಿ ಗುಣಾಃ ಪ್ರಕೃತಿಸಂಭವಾಃ|\nನಿಬಧ್ನಂತಿ ಮಹಾಬಾಹೋ ದೇಹೇ ದೇಹಿನಮವ್ಯಯಮ್||",
    meaningKn: "ಸತ್ವ, ರಜಸ್ಸು ಮತ್ತು ತಮಸ್ಸು ಎಂಬ ಮೂರು ಗುಣಗಳು ಪ್ರಕೃತಿಯಿಂದ ಹುಟ್ಟುತ್ತವೆ; ಇವು ಶಾಶ್ವತ ಆತ್ಮವನ್ನು ದೇಹಕ್ಕೆ ಬಂಧಿಸುತ್ತವೆ.",
    meaningEn: "Sattva (clarity), Rajas (passion) and Tamas (inertia) are the three qualities born of nature; they bind the eternal soul to the body.",
    explanationKn: "ಪ್ರತಿ ಮನಸ್ಥಿತಿ ಅಥವಾ ಕ್ರಿಯೆ ಈ ಮೂರು ಪ್ರವೃತ್ತಿಗಳಲ್ಲಿ ಒಂದರಿಂದ ಬರುತ್ತದೆ — ಸ್ಪಷ್ಟತೆ, ಚಡಪಡಿಕೆ, ಅಥವಾ ಜಡತೆ. ಯಾವುದು ಸಕ್ರಿಯವಾಗಿದೆ ಎಂದು ಗುರುತಿಸುವುದು ಉತ್ತಮ ಆಯ್ಕೆಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    explanationEn: "Every mood or action comes from one of three tendencies — clarity, restless drive, or dullness. Noticing which one is active in you helps you choose a better response.",
    lifeHackKn: "ಪ್ರತಿಕ್ರಿಯಿಸುವ ಮೊದಲು \"ನಾನು ಈಗ ಸ್ಪಷ್ಟತೆಯಿಂದಲೋ, ಚಡಪಡಿಕೆಯಿಂದಲೋ, ಜಡತೆಯಿಂದಲೋ ವರ್ತಿಸುತ್ತಿದ್ದೇನೆಯೇ?\" ಎಂದು ಕೇಳಿ.",
    lifeHackEn: "Before reacting, ask yourself: \"Am I acting from clarity, restlessness, or laziness right now?\" Naming the state is often enough to shift it."
  },
  {
    chapter: 15,
    chapterTitleKn: "ಪುರುಷೋತ್ತಮ ಯೋಗ",
    chapterTitleEn: "The Supreme Person",
    verseRef: "15.7",
    sanskrit: "ಮಮೈವಾಂಶೋ ಜೀವಲೋಕೇ ಜೀವಭೂತಃ ಸನಾತನಃ|\nಮನಃಷಷ್ಠಾನೀಂದ್ರಿಯಾಣಿ ಪ್ರಕೃತಿಸ್ಥಾನಿ ಕರ್ಷತಿ||",
    kannadaChant: "ಮಮೈವಾಂಶೋ ಜೀವಲೋಕೇ ಜೀವಭೂತಃ ಸನಾತನಃ|\nಮನಃಷಷ್ಠಾನೀಂದ್ರಿಯಾಣಿ ಪ್ರಕೃತಿಸ್ಥಾನಿ ಕರ್ಷತಿ||",
    meaningKn: "ನನ್ನ ಶಾಶ್ವತ ಅಂಶವೇ ಈ ಲೋಕದಲ್ಲಿ ಜೀವಾತ್ಮವಾಗಿ, ಪ್ರಕೃತಿಯಲ್ಲಿರುವ ಮನಸ್ಸು ಮತ್ತು ಐದು ಇಂದ್ರಿಯಗಳನ್ನು ತನ್ನೆಡೆಗೆ ಸೆಳೆಯುತ್ತದೆ.",
    meaningEn: "An eternal fragment of Me becomes the living soul in this world, drawing to itself the mind and the five senses rooted in nature.",
    explanationKn: "ನೀವು ಚಿಕ್ಕ, ಪ್ರತ್ಯೇಕ, ಅರ್ಥಹೀನ ಜೀವಿಯಲ್ಲ — ನೀವು ಅದೇ ಶಾಶ್ವತ ಮೂಲದ ಒಂದು ಕಿಡಿಯನ್ನು ಹೊಂದಿದ್ದೀರಿ. ಇದು ಪರಿಸ್ಥಿತಿ ಏನೇ ಇರಲಿ, ಮೂಲಭೂತ ಬೆಲೆಯನ್ನು ಕೊಡುತ್ತದೆ.",
    explanationEn: "You are not a small, separate, insignificant being — you carry a spark of the same eternal source. That gives you inherent worth, no matter what you're going through.",
    lifeHackKn: "ಆತ್ಮವಿಶ್ವಾಸ ಕಡಿಮೆ ಇರುವ ದಿನಗಳಲ್ಲಿ ನೆನಪಿಡಿ: ನೀವು ಶಾಶ್ವತ ಕಿಡಿಯನ್ನು ಹೊಂದಿದ್ದೀರಿ — ಒಂದು ಕೆಟ್ಟ ದಿನ ನಿಮ್ಮ ಪೂರ್ಣ ಬೆಲೆಯನ್ನು ನಿರ್ಧರಿಸದಿರಲಿ.",
    lifeHackEn: "On low self-worth days, remember you carry an eternal spark, not just a temporary identity. Don't let one bad day define your whole worth."
  },
  {
    chapter: 16,
    chapterTitleKn: "ದೈವಾಸುರ ಸಂಪದ್ ವಿಭಾಗ ಯೋಗ",
    chapterTitleEn: "Divine & Demonic Natures",
    verseRef: "16.21",
    sanskrit: "ತ್ರಿವಿಧಂ ನರಕಸ್ಯೇದಂ ದ್ವಾರಂ ನಾಶನಮಾತ್ಮನಃ|\nಕಾಮಃ ಕ್ರೋಧಸ್ತಥಾ ಲೋಭಸ್ತಸ್ಮಾದೇತತ್ತ್ರಯಂ ತ್ಯಜೇತ್||",
    kannadaChant: "ತ್ರಿವಿಧಂ ನರಕಸ್ಯೇದಂ ದ್ವಾರಂ ನಾಶನಮಾತ್ಮನಃ|\nಕಾಮಃ ಕ್ರೋಧಸ್ತಥಾ ಲೋಭಸ್ತಸ್ಮಾದೇತತ್ತ್ರಯಂ ತ್ಯಜೇತ್||",
    meaningKn: "ಕಾಮ, ಕ್ರೋಧ, ಲೋಭ — ಇವು ಆತ್ಮನಾಶದ ಮೂರು ದ್ವಾರಗಳು. ಈ ಮೂರನ್ನೂ ತ್ಯಜಿಸಬೇಕು.",
    meaningEn: "Lust, anger and greed — these are the three gates to self-destruction. One should abandon all three.",
    explanationKn: "ಜೀವನದಲ್ಲಿ ಹೆಚ್ಚಿನ ಸ್ವಯಂ-ಹಾನಿ ಈ ಮೂರರಲ್ಲಿ ಒಂದಕ್ಕೆ ಸೇರುತ್ತದೆ — ಅಗತ್ಯಕ್ಕಿಂತ ಹೆಚ್ಚು ಬಯಸುವುದು, ಕೋಪದಿಂದ ಪ್ರತಿಕ್ರಿಯಿಸುವುದು, ಅಥವಾ ಬಿಗಿಯಾಗಿ ಹಿಡಿದುಕೊಳ್ಳುವುದು.",
    explanationEn: "Most self-sabotage in life traces back to one of these three: craving more than you need, reacting in anger, or holding on too tightly.",
    lifeHackKn: "ಕೆಟ್ಟ ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳುವ ಮೊದಲು ಪರಿಶೀಲಿಸಿ — ಕಾಮ, ಕ್ರೋಧ, ಅಥವಾ ಲೋಭ ಇದನ್ನು ಪ್ರೇರೇಪಿಸುತ್ತಿದೆಯೇ?",
    lifeHackEn: "Before a bad decision, check — is lust, anger, or greed driving this right now? Naming it early is often enough to stop it."
  },
  {
    chapter: 17,
    chapterTitleKn: "ಶ್ರದ್ಧಾತ್ರಯ ವಿಭಾಗ ಯೋಗ",
    chapterTitleEn: "Three Kinds of Faith",
    verseRef: "17.3",
    sanskrit: "ಸತ್ತ್ವಾನುರೂಪಾ ಸರ್ವಸ್ಯ ಶ್ರದ್ಧಾ ಭವತಿ ಭಾರತ|\nಶ್ರದ್ಧಾಮಯೋಽಯಂ ಪುರುಷೋ ಯೋ ಯಚ್ಛ್ರದ್ಧಃ ಸ ಏವ ಸಃ||",
    kannadaChant: "ಸತ್ತ್ವಾನುರೂಪಾ ಸರ್ವಸ್ಯ ಶ್ರದ್ಧಾ ಭವತಿ ಭಾರತ|\nಶ್ರದ್ಧಾಮಯೋಽಯಂ ಪುರುಷೋ ಯೋ ಯಚ್ಛ್ರದ್ಧಃ ಸ ಏವ ಸಃ||",
    meaningKn: "ಪ್ರತಿಯೊಬ್ಬರ ಶ್ರದ್ಧೆ ಅವರ ಮನಸ್ಸಿನ ಸ್ವಭಾವವನ್ನು ಅನುಸರಿಸುತ್ತದೆ. ಮನುಷ್ಯ ತನ್ನ ಶ್ರದ್ಧೆಯಿಂದಲೇ ಮಾಡಲ್ಪಟ್ಟಿದ್ದಾನೆ — ಅವನ ಶ್ರದ್ಧೆ ಹೇಗೋ, ಅವನೂ ಹಾಗೆ.",
    meaningEn: "The faith of every person follows the nature of their mind, O Bharata. A person is made of their faith — as one's faith is, so is the person.",
    explanationKn: "ನೀವು ಆಳವಾಗಿ ನಂಬುವುದೇ ನಿಮ್ಮನ್ನು ರೂಪಿಸುತ್ತದೆ. ನಿಮ್ಮ ನಂಬಿಕೆಗಳನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ಆರಿಸಿ, ಅವು ಮೌನವಾಗಿ ನಿಮ್ಮ ವ್ಯಕ್ತಿತ್ವ ಕಟ್ಟುತ್ತವೆ.",
    explanationEn: "What you deeply believe in shapes who you slowly become. Choose your beliefs carefully, because they quietly build your character over time.",
    lifeHackKn: "ನೀವು ಯಾವುದರಲ್ಲಿ ನಂಬಿಕೆ ಇಟ್ಟಿದ್ದೀರಿ ಎಂದು ಪರಿಶೀಲಿಸಿ — ಅಭ್ಯಾಸಗಳು, ಸ್ನೇಹಿತರು, ನೋಡುವ ವಿಷಯ.",
    lifeHackEn: "Audit what you give your faith to — your habits, your circle, what you consume daily — because you slowly become what you consistently believe in."
  },
  {
    chapter: 18,
    chapterTitleKn: "ಮೋಕ್ಷ ಸಂನ್ಯಾಸ ಯೋಗ",
    chapterTitleEn: "The Yoga of Liberation",
    verseRef: "18.66",
    sanskrit: "ಸರ್ವಧರ್ಮಾನ್ಪರಿತ್ಯಜ್ಯ ಮಾಮೇಕಂ ಶರಣಂ ವ್ರಜ|\nಅಹಂ ತ್ವಾಂ ಸರ್ವಪಾಪೇಭ್ಯೋ ಮೋಕ್ಷಯಿಷ್ಯಾಮಿ ಮಾ ಶುಚಃ||",
    kannadaChant: "ಸರ್ವಧರ್ಮಾನ್ಪರಿತ್ಯಜ್ಯ ಮಾಮೇಕಂ ಶರಣಂ ವ್ರಜ|\nಅಹಂ ತ್ವಾಂ ಸರ್ವಪಾಪೇಭ್ಯೋ ಮೋಕ್ಷಯಿಷ್ಯಾಮಿ ಮಾ ಶುಚಃ||",
    meaningKn: "ಎಲ್ಲಾ ಧರ್ಮಗಳನ್ನು ತ್ಯಜಿಸಿ ನನ್ನೊಬ್ಬನ ಶರಣಾಗು. ನಾನು ನಿನ್ನನ್ನು ಎಲ್ಲಾ ಪಾಪಗಳಿಂದ ಮುಕ್ತಗೊಳಿಸುತ್ತೇನೆ, ದುಃಖಿಸಬೇಡ.",
    meaningEn: "Abandon all other paths and surrender to Me alone. I will liberate you from all sins; do not grieve.",
    explanationKn: "ಗೀತೆಯ ಕೊನೆಯ ಸಂದೇಶ ಸಂಪೂರ್ಣ ನಂಬಿಕೆ ಮತ್ತು ಶರಣಾಗತಿ — ಎಲ್ಲಾ ದಾರಿ, ಬೋಧನೆ, ಪ್ರಯತ್ನದ ನಂತರ, ಸಂಪೂರ್ಣವಾಗಿ ನಂಬಿ ಶರಣಾಗುವ ಕ್ಷಣ ಬರುತ್ತದೆ.",
    explanationEn: "The Gita's final message is radical trust and letting go. After all the paths, teachings and effort, there comes a point where you simply surrender and trust completely.",
    lifeHackKn: "ನಿಮ್ಮ ಕೈಯಲ್ಲಿರುವುದನ್ನೆಲ್ಲಾ ಮಾಡಿದ ನಂತರ, ಬಿಟ್ಟುಬಿಡಿ ಮತ್ತು ಪ್ರಕ್ರಿಯೆಯನ್ನು ನಂಬಿ.",
    lifeHackEn: "After doing everything within your control, let go and trust the process — carrying every outcome alone is a guaranteed path to burnout."
  }
];
